from __future__ import annotations

import argparse
import json
import pickle
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import rhalphalib as rl
import ROOT

from hbb.common_vars import LUMI

# Suppress annoying ROOT warnings
ROOT.gROOT.SetBatch(True)
warnings.filterwarnings("ignore")

rl.util.install_roofit_helpers()

eps = 0.001

# Systematics configuration
do_systematics = True
do_muon_CR = False

lumi_err = {"2022": 1.01, "2023": 1.02}


def plot_mctf(tf_MCtempl, msdbins, name, _year, _tag, out_dir_base):
    """
    Plot the MC pass / fail TF as function of (pt,rho) and (pt,msd)
    """
    import matplotlib.pyplot as plt

    # Create directory
    outdir = Path(out_dir_base) / "plots" / "MCTF"
    outdir.mkdir(parents=True, exist_ok=True)

    # Z-Gamma Low pT Range (200 - 1200)
    pts = np.linspace(200, 1200, 15)
    ptpts, msdpts = np.meshgrid(
        pts[:-1] + 0.5 * np.diff(pts), msdbins[:-1] + 0.5 * np.diff(msdbins), indexing="ij"
    )

    # Scaling
    ptpts_scaled = (ptpts - 200.0) / (1200.0 - 200.0)
    rhopts = 2 * np.log(msdpts / ptpts)
    rhopts_scaled = (rhopts - (-6)) / ((-2.1) - (-6))

    validbins = (rhopts_scaled >= 0) & (rhopts_scaled <= 1)

    ptpts = ptpts[validbins].copy()
    msdpts = msdpts[validbins].copy()
    ptpts_scaled = ptpts_scaled[validbins].copy()
    rhopts_scaled = rhopts_scaled[validbins].copy()

    tf_MCtempl_vals = tf_MCtempl(ptpts_scaled, rhopts_scaled, nominal=True)

    df_plot = pd.DataFrame([])
    df_plot["msd"] = msdpts.reshape(-1)
    df_plot["pt"] = ptpts.reshape(-1)
    df_plot["MCTF"] = tf_MCtempl_vals.reshape(-1)

    # Plot 1: pT vs Mass
    fig, ax = plt.subplots()
    h = ax.hist2d(x=df_plot["msd"], y=df_plot["pt"], weights=df_plot["MCTF"], bins=(msdbins, pts))
    plt.xlabel("$m_{sd}$ [GeV]")
    plt.ylabel("$p_{T}$ [GeV]")
    cb = fig.colorbar(h[3], ax=ax)
    cb.set_label("Ratio (Pass/Fail)")
    fig.savefig(outdir / f"MCTF_msdpt_{name}.png", bbox_inches="tight")
    plt.close()

    # Plot 2: pT vs Rho
    rhos = np.linspace(-6, -2.1, 23)
    ptpts, rhopts = np.meshgrid(
        pts[:-1] + 0.5 * np.diff(pts), rhos[:-1] + 0.5 * np.diff(rhos), indexing="ij"
    )
    ptpts_scaled = (ptpts - 200.0) / (1200.0 - 200.0)
    rhopts_scaled = (rhopts - (-6)) / ((-2.1) - (-6))
    validbins = (rhopts_scaled >= 0) & (rhopts_scaled <= 1)

    ptpts = ptpts[validbins].copy()
    rhopts = rhopts[validbins].copy()
    ptpts_scaled = ptpts_scaled[validbins].copy()
    rhopts_scaled = rhopts_scaled[validbins].copy()

    tf_MCtempl_vals = tf_MCtempl(ptpts_scaled, rhopts_scaled, nominal=True)

    df_plot = pd.DataFrame([])
    df_plot["rho"] = rhopts.reshape(-1)
    df_plot["pt"] = ptpts.reshape(-1)
    df_plot["MCTF"] = tf_MCtempl_vals.reshape(-1)

    fig, ax = plt.subplots()
    h = ax.hist2d(x=df_plot["rho"], y=df_plot["pt"], weights=df_plot["MCTF"], bins=(rhos, pts))
    plt.xlabel(r"$\rho = 2\ln(m_{SD}/p_T)$")
    plt.ylabel("$p_{T}$ [GeV]")
    cb = fig.colorbar(h[3], ax=ax)
    cb.set_label("Ratio (Pass/Fail)")
    fig.savefig(outdir / f"MCTF_rhopt_{name}.png", bbox_inches="tight")
    plt.close()
    print(f"Saved MCTF plots to {outdir}")


def badtemplate(hvalues, mask=None):
    # Need minimum size & more than 1 non-zero bins
    tot = np.sum(hvalues[mask])
    count_nonzeros = np.sum(hvalues[mask] > 0)
    return bool(tot < eps or count_nonzeros < 2)


def get_template(indir, year, sName, region, ptbin, cat, obs, syst):
    """
    Read msd template from root file generated by make_histos.py
    """
    fname = Path(indir) / f"fitting_{year}_control-zgamma.root"
    f = ROOT.TFile.Open(str(fname))

    if not f:
        print(f"ERROR: Could not open {fname}")
        return (
            np.zeros(len(obs.binning) - 1),
            obs.binning,
            obs.name,
            np.zeros(len(obs.binning) - 1),
        )

    reg_clean = region.rstrip("_")
    name = f"{cat}_{reg_clean}_pt{ptbin}_{sName}_{syst}"

    h = f.Get(name)

    if not h:
        return (
            np.zeros(len(obs.binning) - 1),
            obs.binning,
            obs.name,
            np.zeros(len(obs.binning) - 1),
        )

    sumw = []
    sumw2 = []

    for i in range(1, h.GetNbinsX() + 1):
        if h.GetBinContent(i) < 0:
            sumw += [0]
            sumw2 += [0]
        else:
            sumw += [h.GetBinContent(i)]
            sumw2 += [h.GetBinError(i) * h.GetBinError(i)]

    return (np.array(sumw), obs.binning, obs.name, np.array(sumw2))


def get_merged_template(indir, year, process_groups, region, ptbin, cat, obs, syst="nominal"):
    """
    Helper function to sum histograms for a list of processes.
    process_groups: list of tuples like [('Zgamma', 'bb'), ('Zjets', 'bb')]
    """
    merged_sumw = None
    merged_sumw2 = None

    for proc_base, flavor_suffix in process_groups:
        # Construct name logic based on export_to_root in make_histos.py
        # If suffix is "", it maps to "{proc}_nominal"
        # If suffix is "bb", it maps to "{proc}bb_nominal"
        proc_name = proc_base + flavor_suffix

        # Get the template using existing helper
        templ = get_template(indir, year, proc_name, region, ptbin, cat, obs, syst)
        sumw, binning, name, sumw2 = templ

        if merged_sumw is None:
            merged_sumw = np.zeros_like(sumw)
            merged_sumw2 = np.zeros_like(sumw2)

        merged_sumw += sumw
        merged_sumw2 += sumw2

    return (merged_sumw, obs.binning, obs.name, merged_sumw2)


def zgamma_rhalphabet(args):
    year = args.year
    tag = args.tag
    indir = args.indir

    print(f"Running Z-Gamma Card Maker for {year}, reading from {indir}")

    out_dir_base = Path(f"results/{tag}/{year}")
    datacard_dir = out_dir_base / "datacards"
    initvals_dir = out_dir_base / "initial_vals"

    datacard_dir.mkdir(parents=True, exist_ok=True)
    initvals_dir.mkdir(parents=True, exist_ok=True)

    with Path("setup_zgamma.json").open() as f:
        setup = json.load(f)
        cats_cfg = setup["categories"]

    total_model_bins = []
    sys_lumi_uncor = rl.NuisanceParameter(f"CMS_lumi_13TeV_{year[:4]}", "lnN")
    validbins = {}

    msd_cfg = setup["observable"]
    msdbins = np.linspace(msd_cfg["min"], msd_cfg["max"], msd_cfg["nbins"] + 1)
    msd = rl.Observable(msd_cfg["name"], msdbins)

    cats = ["zgcr"]

    # --- 1. QCD ESTIMATION (TF) ---
    tf_params = {}
    for cat in cats:
        ptbins = np.array(cats_cfg[cat]["bins"])
        npt = len(ptbins) - 1

        ptpts, msdpts = np.meshgrid(
            ptbins[:-1] + 0.3 * np.diff(ptbins),
            msdbins[:-1] + 0.5 * np.diff(msdbins),
            indexing="ij",
        )
        rhopts = 2 * np.log(msdpts / ptpts)
        ptscaled = (ptpts - 200.0) / (1200.0 - 200.0)
        rhoscaled = (rhopts - (-6.0)) / ((-1.0) - (-6.0))

        validbins[cat] = (rhoscaled >= 0.0) & (rhoscaled <= 1.0)
        rhoscaled[~validbins[cat]] = 1

        tf_params[cat] = {}
        fitfailed_qcd = {}

        for reg in ["bb"]:
            fitfailed_qcd[reg] = 0

            while fitfailed_qcd[reg] < 5:
                qcdmodel = rl.Model(f"qcdmodel_{cat}_{reg}")
                qcdpass, qcdfail = 0.0, 0.0

                for ptbin in range(npt):
                    failCh = rl.Channel(f"ptbin{ptbin}{cat}fail{year}{reg}")
                    passCh = rl.Channel(f"ptbin{ptbin}{cat}pass{year}{reg}")
                    qcdmodel.addChannel(failCh)
                    qcdmodel.addChannel(passCh)

                    # Using GJets MC for Transfer Factor derivation
                    failTempl = get_template(
                        indir, year, "GJets", "fail_", ptbin + 1, cat, obs=msd, syst="nominal"
                    )
                    passTempl = get_template(
                        indir,
                        year,
                        "GJets",
                        f"pass_{reg}_",
                        ptbin + 1,
                        cat,
                        obs=msd,
                        syst="nominal",
                    )

                    failCh.setObservation(failTempl, read_sumw2=True)
                    passCh.setObservation(passTempl, read_sumw2=True)

                    qcdfail += failCh.getObservation()[0].sum()
                    qcdpass += passCh.getObservation()[0].sum()

                qcdeff = qcdpass / qcdfail
                print(f"Inclusive P/F ({reg}) from Monte Carlo = {qcdeff}")

                initF = initvals_dir / f"initial_vals_{cat}_{reg}.json"
                if initF.exists():
                    with initF.open() as f:
                        initial_vals = np.array(json.load(f)["initial_vals"])
                else:
                    print(f"No initial vals found for {reg}, using default Order 1 poly.")
                    initial_vals = np.array([[1.0, 0.1]])

                tf_MCtempl = rl.BasisPoly(
                    f"tf_MCtempl_{cat}{reg}{year}",
                    (initial_vals.shape[0] - 1, initial_vals.shape[1] - 1),
                    ["pt", "rho"],
                    basis="Bernstein",
                    init_params=initial_vals,
                    limits=(0, 10),
                    coefficient_transform=None,
                )

                tf_MCtempl_params = qcdeff * tf_MCtempl(ptscaled, rhoscaled)

                for ptbin in range(npt):
                    failCh = qcdmodel[f"ptbin{ptbin}{cat}fail{year}{reg}"]
                    passCh = qcdmodel[f"ptbin{ptbin}{cat}pass{year}{reg}"]
                    failObs = failCh.getObservation()[0]

                    qcdparams = np.array(
                        [
                            rl.IndependentParameter(f"qcdparam_ptbin{ptbin}{cat}{year}{reg}_{i}", 0)
                            for i in range(msd.nbins)
                        ]
                    )
                    sigmascale = 10.0
                    scaledparams = (
                        failObs * (1 + sigmascale / np.maximum(1.0, np.sqrt(failObs))) ** qcdparams
                    )

                    fail_qcd = rl.ParametericSample(
                        f"ptbin{ptbin}{cat}fail{year}{reg}_qcd",
                        rl.Sample.BACKGROUND,
                        msd,
                        scaledparams,
                    )
                    failCh.addSample(fail_qcd)

                    pass_qcd = rl.TransferFactorSample(
                        f"ptbin{ptbin}{cat}pass{year}{reg}_qcd",
                        rl.Sample.BACKGROUND,
                        tf_MCtempl_params[ptbin, :],
                        fail_qcd,
                    )
                    passCh.addSample(pass_qcd)

                    failCh.mask = validbins[cat][ptbin]
                    passCh.mask = validbins[cat][ptbin]

                qcdfit_ws = ROOT.RooWorkspace("w")
                simpdf, obs = qcdmodel.renderRoofit(qcdfit_ws)
                qcdfit = simpdf.fitTo(
                    obs,
                    ROOT.RooFit.Extended(True),
                    ROOT.RooFit.SumW2Error(True),
                    ROOT.RooFit.Strategy(2),
                    ROOT.RooFit.Save(),
                    ROOT.RooFit.Minimizer("Minuit2", "migrad"),
                    ROOT.RooFit.PrintLevel(-1),
                )

                if qcdfit.status() != 0:
                    fitfailed_qcd[reg] += 1
                    print(f"Fit failed for {reg}, retrying...")
                else:
                    print(f"Fit successful for {reg}")
                    allparams = dict(zip(qcdfit.nameArray(), qcdfit.valueArray()))
                    pvalues = []
                    for _, p in enumerate(tf_MCtempl.parameters.reshape(-1)):
                        p.value = allparams[p.name]
                        pvalues += [p.value]
                    new_values = np.array(pvalues).reshape(tf_MCtempl.parameters.shape)
                    with initF.open("w") as outfile:
                        json.dump({"initial_vals": new_values.tolist()}, outfile)
                    break

            plot_mctf(tf_MCtempl, msdbins, f"{cat}_{reg}", year, tag, str(out_dir_base))

            param_names = [p.name for p in tf_MCtempl.parameters.reshape(-1)]
            decoVector = rl.DecorrelatedNuisanceVector.fromRooFitResult(
                tf_MCtempl.name + "_deco", qcdfit, param_names
            )
            tf_MCtempl.parameters = decoVector.correlated_params.reshape(
                tf_MCtempl.parameters.shape
            )

            res_order = (0, args.order)
            new_init_params = np.ones((res_order[0] + 1, res_order[1] + 1))

            tf_dataResidual = rl.BasisPoly(
                f"tf_dataResidual_{year}{cat}{reg}",
                res_order,
                ["pt", "rho"],
                basis="Bernstein",
                init_params=new_init_params,
                limits=(0, 20),
                coefficient_transform=None,
            )

            tf_params[cat][reg] = (
                qcdeff * tf_MCtempl(ptscaled, rhoscaled) * tf_dataResidual(ptscaled, rhoscaled)
            )

    # --- 2. BUILD ACTUAL MODEL WITH CRISTINA GROUPING ---
    model = rl.Model("zgammaModel_" + year)

    # PROCESS GROUPING DEFINITIONS
    process_groups = {
        "zgammabb": {"components": [("Zgamma", "bb"), ("Zjets", "bb")], "is_signal": True},
        "wgammacs": {
            # Note: "bb" is used here because make_histos currently dumps charm into light.
            # Once make_histos splits "cc", change this to [("Wgamma", "cc"), ("Wjets", "cc")]
            "components": [("Wgamma", "bb"), ("Wjets", "bb")],
            "is_signal": False,
        },
        "other": {
            # Empty suffix "" maps to unmatched/light component
            "components": [
                ("Zgamma", ""),
                ("Zjets", ""),
                ("Wgamma", ""),
                ("Wjets", ""),
                ("ttbar", ""),
                ("TTGamma", ""),
                ("singlet", ""),
                ("VV", ""),
            ],
            "is_signal": False,
        },
    }

    for cat in cats:
        ptbins = np.array(cats_cfg[cat]["bins"])
        npt = len(ptbins) - 1

        for ptbin in range(npt):
            for region in ["pass_bb_", "fail_"]:
                ch_name = f"ptbin{ptbin}{cat}{region.replace('_', '')}{year}"
                total_model_bins.append(ch_name)
                ch = rl.Channel(ch_name)
                model.addChannel(ch)

                # Iterate over groups instead of individual samples
                for proc_label, group_info in process_groups.items():

                    templ = get_merged_template(
                        indir,
                        year,
                        group_info["components"],
                        region,
                        ptbin + 1,
                        cat,
                        obs=msd,
                        syst="nominal",
                    )
                    nominal = templ[0]

                    # Threshold Check for WGammaCS
                    if proc_label == "wgammacs" and np.sum(nominal) < 0.1:
                        # print(f"Skipping {proc_label} in {ch_name} (Yield < 0.1)")
                        continue

                    if badtemplate(nominal):
                        continue

                    stype = rl.Sample.SIGNAL if group_info["is_signal"] else rl.Sample.BACKGROUND
                    sample = rl.TemplateSample(ch.name + "_" + proc_label, stype, templ)

                    sample.setParamEffect(
                        sys_lumi_uncor,
                        lumi_err[year[:4]] ** (LUMI[year[:4]] / LUMI["2022-2023"]),
                    )

                    if do_systematics:
                        # AutoMCStats works because we summed the sumw2 correctly
                        sample.autoMCStats(lnN=True)

                    ch.addSample(sample)

                # Using EGammadata (Data)
                data_obs = get_template(
                    indir, year, "data_obs", region, ptbin + 1, cat, obs=msd, syst="nominal"
                )
                ch.setObservation(data_obs[0:3])

    # --- 3. ADD DATA-DRIVEN QCD (UPDATED SUBTRACTION) ---
    for cat in cats:
        ptbins = np.array(cats_cfg[cat]["bins"])
        npt = len(ptbins) - 1

        for ptbin in range(npt):
            failCh = model[f"ptbin{ptbin}{cat}fail{year}"]
            passChbb = model[f"ptbin{ptbin}{cat}passbb{year}"]

            qcdparams = np.array(
                [
                    rl.IndependentParameter(f"qcdparam_ptbin{ptbin}{cat}{year}_{i}", 0)
                    for i in range(msd.nbins)
                ]
            )
            initial_qcd = failCh.getObservation().astype(float)

            # Subtract grouped backgrounds
            for sample in failCh:
                initial_qcd -= sample.getExpectation(nominal=True)

            if np.any(initial_qcd < 0.0):
                initial_qcd[np.where(initial_qcd < 0)] = 0
                print(f"Warning: negative QCD estimate in {failCh.name}")

            sigmascale = 20
            scaledparams = (
                initial_qcd * (1 + sigmascale / np.maximum(1.0, np.sqrt(initial_qcd))) ** qcdparams
            )

            fail_qcd = rl.ParametericSample(
                name=f"ptbin{ptbin}{cat}fail{year}_qcd",
                sampletype=rl.Sample.BACKGROUND,
                observable=msd,
                params=scaledparams,
            )
            failCh.addSample(fail_qcd)

            pass_qcdbb = rl.TransferFactorSample(
                name=f"ptbin{ptbin}{cat}passbb{year}_qcd",
                sampletype=rl.Sample.BACKGROUND,
                transferfactor=tf_params[cat]["bb"][ptbin, :],
                dependentsample=fail_qcd,
                observable=msd,
            )
            passChbb.addSample(pass_qcdbb)

            mask = validbins[cat][ptbin]
            failCh.mask = mask
            passChbb.mask = mask

    # --- 4. SAVE OUTPUT ---
    with (datacard_dir / f"zgammaModel_{year}.pkl").open("wb") as fout:
        pickle.dump(model, fout)

    modeldir = datacard_dir / f"zgammaModel_{year}"
    model.renderCombine(modeldir)

    out_cards = ""
    for card in total_model_bins:
        out_cards += f"{card}={card}.txt "
        with Path(f"{modeldir}/{card}.txt").open("a") as f:
            f.write("\nqcd_norm rateParam * qcd 1.0 [0,20]\n")

    # Physics Model: Map zgammabb (New Name) to signal strength 'r'
    t2w_cfg = "-P HiggsAnalysis.CombinedLimit.PhysicsModel:multiSignalModel --PO verbose --PO 'map=.*/zgammabb:r[1,-100,100]'"

    with (modeldir / "build.sh").open("w") as f:
        f.write(f"combineCards.py {out_cards} > model_combined.txt\n")
        f.write(f"text2workspace.py {t2w_cfg} model_combined.txt -o workspace.root\n")

    print(f"Datacards saved to {modeldir}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--year", help="year", type=str, required=True)
    parser.add_argument("--tag", help="tag", type=str, required=True)
    parser.add_argument(
        "--indir", help="Input dir containing fitting_*.root", type=str, required=True
    )
    parser.add_argument(
        "--order", help="Polynomial order for DataResidual (pt, rho)", type=int, default=0
    )

    args = parser.parse_args()
    zgamma_rhalphabet(args)
